funnypages/funnypages/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('viewer.urls', namespace="viewer", app_name="viewer"))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

funnypages/viewer/urls.py
from django.conf.urls import patterns, url
from viewer.views import LandingPageView

urlpatterns = patterns('',
    url(r'^$', LandingPageView.as_view(), name='landingpage'),
    url(r'^edit/(?P<collection_id>\d+)/$', 'viewer.views.edit', name='edit'),
    url(r'^create/$', 'viewer.views.create', name='create'),
    url(r'^collection/(?P<collection_id>\d+)/$', 'viewer.views.viewer', name='viewer'),
    url(r'^submission/', 'viewer.views.request_confirmation', name='request_confirmation')
)

funnypages/funnypages_viewer/models.py
from django.db import models

class ComicSeries(models.Model):

    name = models.CharField(max_length=200)
    homepage = models.URLField(max_length=200)
    def __unicode__(self):
        return self.name

class ComicImg(models.Model):

    series = models.ForeignKey(ComicSeries)
    name = models.CharField(max_length=200)
    img = models.FileField(upload_to='comic_img')
    def __unicode__(self):
        return self.name

funnypages/viewer/models.py
import os
from django.db import models
from django.core.urlresolvers import reverse
import requests
from bs4 import BeautifulSoup
from django.conf import settings
from datetime import datetime
from boto.s3.connection import S3Connection
from boto.s3.key import Key


class ComicSeries(models.Model):
    """A webcomic (eg. Penny Arcade, PvP, etc.)"""
    name = models.CharField(max_length=200)
    url = models.URLField(max_length=200)

    def __unicode__(self):
        return self.name

    def download_newest_comic(self):
        """Downloads the newest image for a webcomic and creates a ComicImg object for it"""
        newest_comic_url = self.get_newest_comic_url()
        comic_filename = newest_comic_url.split('/')[-1]
        #create a connection to the the image server
        conn = S3Connection(settings.ACCESS_KEY, settings.PASS_KEY)
        bucket = conn.get_bucket("funnypages")
        k = Key(bucket)
        image_path = 'comic_images/'
        existing_comics = []

        #check the targeted file name against other comics in the comic_img media directory
        for l in bucket.list():
            existing_comics += str(l.key)

        if comic_filename in existing_comics:
            return

        else:
            #use that object as an argument to download a target html resource to the comic image media subdirectory
            img_url = requests.get(newest_comic_url)
            img = open(comic_filename, 'wb')
            img.write(img_url.content)
            img.close()
            k.key = os.path.join(image_path, comic_filename)
            k.set_contents_from_filename(comic_filename)
            os.remove(comic_filename)
            #create an entry in the comic_img model and use the path of the downloaded image to create the img_field
            new_comic_image = ComicImg(name=comic_filename, series=self, pub_date=datetime.now())
            new_comic_image.save()
            
    def get_newest_comic_url(self):
        """Finds the url for a webcomic's newest image"""
        #create a beautiful soup instance for the target comic html
        soup = BeautifulSoup(requests.get(self.url).text)
        #use soup.find to return the src attribute of the target comic and store it in an object.
        if self.name == 'Dr. McNinja' or self.name == 'xkcd':
            return soup.find(id='comic').find('img').attrs['src']

        elif self.name == 'CTRL ALT DEL':
            return soup.find(id='content').find('img').attrs['src']

        else:
            raise Exception('%s is not a supported comic' % self.name)


class ComicImg(models.Model):
    """An comic page from a comic series"""
    series = models.ForeignKey(ComicSeries, related_name='images')
    name = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    class Meta:
        get_latest_by = "pub_date"

    def __unicode__(self):
        return self.name


class Collection(models.Model):
    """A collection of webcomics that can be called up for display"""
    name = models.CharField(max_length=200)
    user = models.ForeignKey("User")
    series = models.ManyToManyField(ComicSeries, related_name="collections")

    def __unicode__(self):
        return self.name

    @property
    def url(self):
        return reverse('viewer:viewer', kwargs={'collection_id': self.id})


class User(models.Model):
    """A class for storing user data"""
    username = models.CharField(max_length = 200)
    password = models.CharField(max_length = 24)

    def __unicode__(self):
        return self.username


class SubmissionLog(models.Model):
    """A class for storing requests for new comics"""
    name = models.CharField(max_length=200)
    sub_date = models.DateTimeField()

funnypages/viewer/forms.py
from django import forms
from viewer.models import Collection, SubmissionLog


class CollectionForm(forms.ModelForm):
    """A for for creating new collections on the create page"""
    class Meta:
        model = Collection
        fields = ('name', 'user', 'series')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Collection Name'}),
            'series': forms.CheckboxSelectMultiple(),
            'user': forms.HiddenInput(),
        }


class CollectionSelectForm(forms.Form):
    """A form for selecting a collection to view in the header of every page"""
    collections = forms.ModelChoiceField(queryset=Collection.objects.all(), empty_label='View a Collection',
                                         to_field_name='url')


#These forms need prefixes!

funnypages/viewer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from viewer.models import Collection, SubmissionLog
from viewer.forms import CollectionForm, CollectionSelectForm
from datetime import datetime
from django.views.generic import TemplateView


class LandingPageView(TemplateView):
    template_name = 'viewer/landingpage.html'


def request_confirmation(request):
    if request.method == 'POST':
        c = SubmissionLog(name=request.POST['newtitle'], sub_date=datetime.now())
        c.save()

    return render(request, 'viewer/request_confirmation.html')


def edit(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    form = CollectionForm(instance=collection)
    if request.method == 'POST':
        form = CollectionForm(request.POST, instance=collection)
        if form.is_valid():
            update_collection = form.save()
            return redirect('viewer:viewer', collection_id=update_collection.id)

    return render(request, 'viewer/edit.html', {
        'form': form,
        'collectionselectform': CollectionSelectForm(),
    })


def create(request):
    if request.method == 'POST':
        form = CollectionForm(request.POST)
        if form.is_valid():
            new_collection = form.save()
            return redirect('viewer:viewer', collection_id=new_collection.id)
    else:
        form = CollectionForm(initial={'user': '1'})

    return render(request, 'viewer/create.html', {
        'form': form,
    })


def viewer(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    series_selection = collection.series.all()
    image_set = []
    for series in series_selection:
        image = series.images.order_by('-pub_date')[:1]
        image_set += image
    return render(request, 'viewer/viewer.html', {
        'collection': collection,
        'image_set': image_set,
        })

funnypages/viewer/templates/homepage/home.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

funnypages/viewer/templates/viewer/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>FUNNYPAGES</title>

    <link rel="stylesheet" type='text/css' href="{% static 'viewer/css/normalize.css' %}" />
    <link rel="stylesheet" type='text/css' href="{% static 'viewer/css/styles.css' %}" />
    <script src="{% static 'viewer/scripts/jquery.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#id_collections').change(function(){
                window.location=this.value;
            })
        })
    </script>
</head>

<body>

    <!-- HEADER -->
    <header>
        <!-- ADD A COLLECTION -->
        <a class="add" href={% url "viewer:create" %}><p><img src="{% static "viewer/images/addicon.png" %}" />ADD COLLECTION</p></a>

        <!-- View a Collection Dropdown -->
        <div id="collectionDropDown">
            {{ collectionselectform.as_p }}
        </div>
    </header>

    <!-- LOGO -->
    <div class="logo-container">
        <a href="{% url "viewer:landingpage" %}"><img class="logo" src="{% static 'viewer/images/Funnypages-logo.png' %}" alt="FUNNYPAGES" /></a>
    </div>


    {% block content %}{% endblock %}


    <!-- FOOTER -->
    <footer>
        <div class="container">
            <div class="row">
                <div class=column-half>
                    <h2>REQUEST A COMIC</h2>

                    <p class="fgen">Submit requests for new comics here.  Just enter the title of the series and click submit!</p>

                    <form action="{% url 'viewer:request_confirmation' %}" method="post">
                        {% csrf_token %}
                        <input type="text" class="comrequest" id="newtitle" name="newtitle" placeholder="Series Title">

                        <input type="submit" value="" class="submit" name="comicrequest">
                    </form>
                </div> <!-- end column-half -->
                <div class=column-half>
                    <p class="adam">Adam Carr | Python Developer</p>
                    <p class="fgen">York, Pennsylvania</p>

                    <a class="email" href="mailto:carr.adam@gmail.com"><p>carr.adam@gmail.com</p></a>

                    <ul class="social">
                        <li><a href="http://www.linkedin.com/pub/adam-carr/a/925/978/"><img src="{%  static "viewer/images/LinkedIn.png" %}" /></a></li>
                        <li><a href="http://www.snaketrials.com"><img src="{%  static "viewer/images/wordpress.png" %}" /></a></li>
                        <li><a href="https://github.com/HamboneWilson"><img src="{%  static "viewer/images/git.png" %}" /></a></li>
                    </ul>
                </div> <!-- end column-half -->
            </div> <!-- end row -->
        </div> <!-- end container -->
    </footer>
</body>

</html>

funnypages/viewer/templates/viewer/create.html
{% extends 'create_edit_base.html' %}
{% load staticfiles %}



{% block center-container %}
<h2>CREATE A COLLECTION</h2>

<p id="create1">Choose your titles, name your collection, and create!</p>
<p>Is your favorite title missing?  Use the request a comic form below!</p>
{% endblock %}

funnypages/viewer/templates/viewer/create_edit_base.html
{% extends 'base.html' %}
{% load staticfiles %}

<!-- Create Page Content -->
{% block content %}
<div class="create-edit-container">
    <div class="center-container">
        {% block center-container %}
        <h2>CREATE A COLLECTION</h2>

        <p id="create1">Choose your titles, name your collection, and create!</p>
        <p>Is your favorite title missing?  Use the request a comic form below!</p>
        {% endblock center-container %}
    </div> <!-- end center-container -->
    <div class="checkboxes">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.name }}
            {{ form.series }}
            {{ form.user }}
            <input class="save" type='submit' value="" />
        </form>
    </div> <!-- end checkboxes -->
</div> <!-- end create-edit-container -->
{% endblock %}

funnypages/viewer/templates/viewer/edit.html
{% extends 'create_edit_base.html' %}
{% load staticfiles %}


{% block center-container %}
<h2>EDIT COLLECTION</h2>

<p>Edit the details of a collection here.</p>
{% endblock %}

funnypages/viewer/templates/viewer/landingpage.html
{% extends 'base.html' %}
{% load staticfiles %}



{% block content %}
<!-- LANDING PAGE CONTENT -->
<div class="lp-container">
    <div class="center-container">
        <h2>A NEW WAY TO VIEW YOUR WEBCOMICS</h2>

        <p>Funnypages offers an elegant way to manage all your favorite webcomics in one self updating page in 3 easy steps.</p>

        <!-- STEPS -->
        <p class="steps">CREATE A COLLECTION</p>
        <p class="steps">SELECT THE COMICS YOU WANT TO FOLLOW</p>
        <p class="steps">SAVE AND VIEW YOUR COLLECTION</p>

        <!-- GET STARTED BUTTON -->
        <div class="btn-content"><a href="{% url 'viewer:create' %}"><img src="{% static "viewer/images/button-get-started.jpg" %}" /></a></div>
    </div> <!-- end center-container -->
</div> <!-- end lp-container -->
{% endblock %}

funnypages/viewer/templates/viewer/request_confirmation.html
{% extends 'base.html' %}
{% load staticfiles %}



{% block content %}
<!--- Comic Request Confirmation Content --->
<div class="lp-container">
    <div class="center-container">

        <p>Thank you for your request!  We will work on adding that title to the comic list as soon as possible.</p>

        <a href="{% url 'viewer:landingpage' %}">Go Home</a>
    </div>
</div>
{% endblock %}

funnypages/viewer/templates/viewer/viewer.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- SUBHEADER -->
<div class="subheader-container">
    <ul id="subheader">
        <li><h2>{{ collection.name }}</h2></li>
        <li><a class="edit" href="{% url 'viewer:edit' collection.id %}">Edit</a></li>
    </ul>
</div> <!-- end container -->
<hr class="hr-subheader" />



<!-- COMIC VIEW -->
<div class="comicImagesContainer">
    {% for image in image_set %}
        <ul class="comicImage">
            <li>{{ image.series }}</li>
            <li>{{ image.pub_date }}</li>
            <li><img src="https://s3.amazonaws.com/funnypages/comic_images/{{ image.name }}" /></li>
        </ul>
    {% endfor %}
</div><!-- end comicImagesContainer -->
{% endblock %}